### ISSUE TITLE
Pacbot not working?

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacbot#391]
Seems like the latest issue opened by pacbot is from Nov 18th 2023.

**Comment by Elsie19** [comment]
We're aware. It's an issue with how the website is storing repology data. It should hopefully be up this week.

**Comment by Elsie19** [comment]
https://github.com/pacstall/website/pull/714

This should fix it. We found out two things from this:

1. It's very slow to download info
2. We can skip some ginormous libs

**Comment by Elsie19** [comment]
Alright pacbot should be working now.

**Comment by Zahrun** [comment]
Pacbot opened many issues, yay!
For some reason, they were all closed as completed even though the packages were not updated.

**Comment by Elsie19** [comment]
So pacbot had a stroke and started opening duplicate issues without seeing the open ones already and not closing the old ones, so I killed it and turned off pacbot for now. I will be doing some investigating tomorrow as to why that happened.

**Comment by Zahrun** [comment]
Ok thanks
